univelop/yust_ui

- lib/src/widgets/yust_text_field.dart
> Add check for value change to prevent rebuild

- lib/src/widgets/yust_text_field.dart
When the YustTextField gets removed from the Widget-Tree without a focus change beforehand the changes of the widget dont trigger onEditingComplete. This PR changes the behaviour to allways call onEditingComplete after the widget was deactivated, dispossed or got a new label.
> Fix: Save YustTextField on deactivate/dispose

- lib/src/widgets/yust_date_picker.dart
- lib/src/widgets/yust_time_picker.dart
- pubspec.lock
- pubspec.yaml
Adds support for [this Yust-PR](https://d51.tech/UXVa).
It also updates the YustDate- & YustTime-Picker to work with UTC Dates ( the UI will still show local, non-utc dates. )
> Feature: Timezone-Support

- lib/src/widgets/yust_list_tile.dart
- lib/src/widgets/yust_number_field.dart
related PR:
- https://github.com/univelop/univelop/pull/1170
> add textStyle option to YustListTile and YustNumberField

- lib/src/screens/yust_image_drawing_screen.dart
- lib/src/util/yust_file_handler.dart
- lib/src/widgets/yust_file_picker.dart
- lib/yust_ui.dart
Necessary changes for creation of DrawingBrick (see pull request #1230)
> Enhancement: Small changes to file handling

- lib/src/widgets/yust_date_picker.dart
Needed for [#1468](https://github.com/univelop/univelop/pull/1468) in Univelop
> Added firstDate and lastDate parameters

- lib/src/services/yust_alert_service.dart
related PR:
- https://github.com/univelop/univelop/pull/2024
> add warning text and suffix icon options to text field dialog

- lib/src/widgets/yust_text_field.dart
related PR:
- https://github.com/univelop/univelop/pull/2004
> reset initText on unfocus

- lib/src/services/yust_alert_service.dart
Add optional subtitle option for pickerDialog
> add optional subtitle

- lib/src/widgets/yust_file_picker.dart
- lib/src/widgets/yust_text_field.dart
Related PR:
- https://github.com/univelop/univelop/pull/2092
> File picker and text field improvement

- lib/src/services/yust_alert_service.dart
- lib/src/widgets/yust_select.dart
- lib/src/widgets/yust_select_form.dart
- lib/src/widgets/yust_select_multiple.dart
- lib/yust_ui.dart
depends on:
- https://github.com/univelop/yust/pull/263
related to:
- https://github.com/univelop/univelop/pull/2329
> rename YustMultiSelectComponent to YustSelectForm

- lib/src/widgets/yust_select.dart
- lib/src/widgets/yust_select_form.dart
- lib/src/widgets/yust_select_multiple.dart
- pubspec.yaml
related to:
- https://github.com/univelop/univelop/pull/2450
> Dynamic yust select

- lib/src/widgets/yust_text_field.dart
related to:
- https://github.com/univelop/univelop/pull/2502
> allow completion of invalid input

- lib/src/widgets/yust_image_picker.dart
- lib/src/widgets/yust_input_tile.dart
- lib/src/widgets/yust_select.dart
related to:
- https://github.com/univelop/univelop/pull/2536
> Fix yust image picker delete bug

- lib/src/services/yust_alert_service.dart
related to:
- https://github.com/univelop/univelop/pull/2160
> Allow 5 lines of validator messages in TextFieldDialog

- pubspec.yaml
- Upgrades most packages (those without breaking changes) to their latest version.
- Removes unused packages
> Upgrade Packages

- lib/src/widgets/yust_list_tile.dart
Belongs to [#2760](https://github.com/univelop/univelop/pull/2761)
> #2760 Add labelOverflow option

- lib/src/services/yust_alert_service.dart
Improve state of clearable picker dialog
> Improve clearable picker dialog

- lib/src/widgets/yust_number_field.dart
Improve handling of numbers when decimalCount is set to 0
> Truncate number field when zero decimal count

- lib/src/generated/locale_keys.g.dart
- lib/src/widgets/yust_file_picker.dart
- lib/src/widgets/yust_image_picker.dart
Closed the old PR and opened this one because I changed the name of the branch
@janneskoehler I approved the old PR but cannot approve this one since I opened it
> 2854 yust UI overwrite document

- lib/src/services/yust_alert_service.dart
Belongs to https://github.com/univelop/univelop/pull/3149.
> Added obscureText to alert

- lib/src/generated/locale_keys.g.dart
- lib/src/widgets/yust_number_field.dart
- lib/src/widgets/yust_text_field.dart
- lib/src/widgets/yust_time_picker.dart
related To:
- https://github.com/univelop/univelop/pull/3273
> Refactor number field and time picker

- lib/src/widgets/yust_input_tile.dart
- lib/src/widgets/yust_text_field.dart
Belongs to:
https://github.com/univelop/univelop/pull/3218
> Added labelStyle

- lib/src/widgets/yust_number_field.dart
related To:
- https://github.com/univelop/univelop/pull/3383
> allow YustNumberField to disable complete on unfocus

- lib/src/generated/locale_keys.g.dart
- lib/src/widgets/yust_paginated_list_view.dart
releated:
- https://github.com/univelop/univelop/pull/3115
> add loadingWidget and ErrorBuilder to Params of PaginatedListView

- lib/src/util/yust_file_handler.dart
Related issue in univelop repo [3771](https://github.com/univelop/univelop/issues/3771).
> Fixed concurrent modification

- lib/src/util/yust_file_helpers.dart
- lib/src/widgets/yust_image_picker.dart
DEPENDS ON https://github.com/univelop/univelop/pull/3761
> Shared images do not get resized

- lib/src/widgets/yust_select_form.dart
This PR closes http://github.com/univelop/univelop/issues/4097
> #4097: Convert stateless selectform to stateful widget

- lib/src/services/yust_alert_service.dart
Couldn't recreate the Issue from this [branch](https://github.com/orgs/univelop/projects/1/views/11?pane=issue&itemId=72225085). 
But realized the virtual keyboard blocks the textfield to type the workspace name. Its a fix for that issue.
> #3667 added scrollability to showTextFieldDialog

- lib/src/screens/yust_image_drawing_screen.dart
- lib/src/screens/yust_image_screen.dart
- lib/src/widgets/yust_image_picker.dart
related to:
- https://github.com/univelop/univelop/pull/3522
> implement navigateToScreen methods for all screens

- lib/src/generated/locale_keys.g.dart
- lib/src/widgets/yust_file_picker.dart
Close [#3056](https://github.com/univelop/univelop/issues/3056)
> Improve YustFilePicker

- lib/src/widgets/yust_cached_image.dart
- lib/src/widgets/yust_text_field.dart
Related to Store issue in Univelop repository
> Loading spinner cached image

- lib/src/screens/yust_image_screen.dart
- lib/src/widgets/yust_image_picker.dart
Closes https://github.com/univelop/univelop/issues/4628
- Added a new property [allowDrawing]
> #4628: Add property to allowDrawing on images

- lib/src/widgets/yust_focusable_builder.dart
- lib/src/widgets/yust_input_tile.dart
- lib/src/widgets/yust_list_tile.dart
- lib/src/widgets/yust_number_field.dart
Closes https://github.com/univelop/univelop/issues/4753
> #4753: Update on focus excluding

- lib/src/widgets/yust_dropzone_list_tile.dart
- lib/src/widgets/yust_focusable_builder.dart
- lib/src/widgets/yust_focused_highlight_wrapper.dart
- lib/src/widgets/yust_select_form.dart
> Revert "Fix lints"

- lib/src/screens/yust_sign_up_screen.dart
- lib/src/widgets/yust_dropzone_list_tile.dart
> #4131 using createAccount instead of signUp

- lib/src/generated/locale_keys.g.dart
- lib/src/screens/yust_sign_up_screen.dart
- lib/src/widgets/yust_dropzone_list_tile.dart
- pubspec.yaml
Used by: https://github.com/univelop/univelop/pull/4902
> #4105: Bump photo view to 0.15.0

- lib/src/util/yust_file_handler.dart
Issue: Can not upload images on mobile device
> Fix image caching

- lib/src/widgets/yust_number_field.dart
- lib/src/widgets/yust_text_field.dart
Fixes https://github.com/univelop/univelop/issues/5284
> #5284: change padding on textfield and number field

- lib/src/generated/locale_keys.g.dart
- lib/src/widgets/yust_text_field.dart
This PR add the maxLength parameter to the YustTextField as an optional value.
> add maxLength to textfield

- CHANGELOG.md
- lib/src/services/yust_alert_service.dart
- lib/src/widgets/yust_input_tile.dart
- lib/src/widgets/yust_select.dart
- lib/src/widgets/yust_select_form.dart
- lib/src/widgets/yust_text_field.dart
- pubspec.yaml
Add the option to add a prefix icon before the textfield
> Add custom comparable option select
